---
- name: Copy Folder to Host
  hosts: all
  become: true

  tasks:
    - name: Copy folder from controller to host
      copy:
        src: /home/controller/Desktop/ansibleScenarioConfigs/nginx-container
        dest: /home/host/Desktop/ANSIBLE
