---
- hosts: all
  become: true
  tasks:
    - name: Copy nginx.conf
      ansible.builtin.copy:
        src: ../nginx-container/nginx.conf
        dest: /tmp/nginx.conf

    - name: Build and run nginx container
      ansible.builtin.shell: |
        docker run -d -p 8000:80 --name nginx-container --network host -v /tmp/nginx.conf:/etc/nginx/nginx.conf nginx:latest
