---
- name: Run Docker Container on Host
  hosts: all
  become: true

  tasks:
    - name: Run Docker container
      docker_container:
        name: nginx-lb  # Desired name for the Docker container
        image: nginx-image   # The name of the Docker image you built
        state: started            # Ensure the container is started
        ports:
          - "9999:9999"              # Example mapping of port 80 in the container to port 8080 on the host
