---
- name: Run Docker Container on Host
  hosts: all
  become: true

  tasks:
    - name: Run Docker container
      docker_container:
        name: nginx-lb  
        image: nginx-image  
        state: started            
        ports:
          - "9999:9999"              
